### ISSUE TITLE
Better instructions

### ISSUE THREAD

**Issue by ArcaneFired** [xaukael/discord-speaking-status#2]
This is a good idea, however your instructions are pretty minimal and there is no FAQs or troubleshooting guides.

Even screen by screen of what things should look like or a way to contact you to discuss the issues.

**Comment by xaukael** [comment]
I can be contacted through here, obviously, or on discord at Allen#2471 (Xaukael in the foundry discord). I had hoped to make this simple enough to make it widely accessible, but as it is, there are technical skills necessary not only to make it work as the GM, but for the players as well. I could potentially reduce the instructions necessary to implement this even further, but I fear there is a threshold of understanding what you are doing that is necessary.

That being said, there are only a few technical obstacles:
- Retrieving and storing the channel ID in the settings
- Retrieving and storing the User ID for each user
- Opening the streamkit window properly
- Running the javascript I provided within the streamkit window (what I was hoping to avoid with a chrome extension)

Which of these is giving you trouble?

**Comment by xaukael** [comment]
Resolved several issues in Discord DM's. I may expand the instructions further in the future.
